language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master # build master branch only
# 设置缓存文件
cache:
  directories:
    - node_modules

install:
  - npm install hexo-theme-next --save
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-searchdb --save
  - npm install hexo-wordcount --save
  - npm install hexo-abbrlink --save
  - npm install lozad --save
  - npm uninstall hexo-generator-index --save
  - npm install hexo-generator-index-pin-top --save
  - npm install hexo-algolia --save

before_script:
  - git config user.name "nimbusking"
  - git config user.email "nimbusking@hotmail.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  - sed -i "s/algolia_applicationID/${ALGOLIA_APPLICATIONID}/g" ./_config.yml
  - sed -i "s/algolia_apiKey/${ALGOLIA_APIKEY}/g" ./_config.yml
  - sed -i "s/algolia_indexName/${ALGOLIA_INDEXNAME}/g" ./_config.yml
  - sed -i "s/gitalk_client_id/${GITALK_CLIENT_ID}/g" ./_config.next.yml
  - sed -i "s/gitalk_client_secret/${GITALK_CLIENT_SECRET}/g" ./_config.next.yml
  # - pwd
  # clone自定义配置
  - git clone -b customer_config https://github.com/nimbusking/nimbusking.github.io.git temp
  - cp -f ./temp/post-meta.njk ./node_modules/hexo-theme-next/layout/_partials/post
  - rm -rf ./temp

script:
  - hexo clean
  - hexo generate
  - hexo algolia
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public