# 脚本2，仅供有其他需要在部署前运行的插件（如gulp、hexo-bangumi-bilibili等）的博客使用，请根据自己博客的实际情况修改下面的脚本代码
name: hexo_blog_audo_deploy
on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: master

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g --save

    - name: 缓存 Hexo
      id: cache
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install hexo-theme-next --save
        npm install hexo-deployer-git --save
        npm install hexo-generator-searchdb --save
        npm install hexo-generator-feed
        npm install hexo-wordcount --save
        npm install hexo-abbrlink --save
        npm install lozad --save
        npm uninstall hexo-generator-index --save
        npm install hexo-generator-index-pin-top --save
        npm install --save

    - name: 配置环境
    
